---
title: "Practical Three"
---

## 1. Display the flights dataset in an alternative format to simply printing it

```{r}
library(nycflights13)
library(tidyverse)

# using the flights dataset
glimpse(flights)
```

## 2. Rewrite the following code using dplyr and the pipe.

The code that needs to be re-written:

```{r}
flight1 <- flights[flights$month == 1, ]
carrier_vec <- unique(flight1$carrier)
carrier_dist_vec_mean <- numeric(length(carrier_vec))
carrier_dist_vec_sd <- numeric(length(carrier_vec))
for (i in seq_along(carrier_vec)) {
  carrier_dist_vec_mean[i] <- mean(
    flight1$distance[flight1$carrier == carrier_vec[i]]
   )
  carrier_dist_vec_sd[i] <- sd(
    flight1$distance[flight1$carrier == carrier_vec[i]]
  )
}
dist_tbl <- tibble(
  carrier = carrier_vec,
  mean_distance = carrier_dist_vec_mean,
  sd_distance = carrier_dist_vec_sd
)
dist_tbl[order(dist_tbl$mean_distance), ]
```

The re-written code:

```{r}
library(dplyr)

dist_tbl <- flights |>
  filter(month == 1) |>
  group_by(carrier) |>
  summarise(mean_distance = mean(distance), sd_distance = sd(distance)) |>
  arrange(mean_distance)
dist_tbl
```
